[build]
  builder = "DOCKERFILE"
  dockerfilePath = "backend/Dockerfile"

[deploy]
  startCommand = "dotnet ClassifiedsAPI.dll"
  
[env]
  ASPNETCORE_ENVIRONMENT = "Production"
  ASPNETCORE_URLS = "http://*:$PORT"